<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $firstname
 * @property string $lastname
 * @property blob $game_board
 * @property integer $game_time
 * @property timestamp $last_action_at
 * @property Doctrine_Collection $Hiscore
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method string              getFirstname()      Returns the current record's "firstname" value
 * @method string              getLastname()       Returns the current record's "lastname" value
 * @method blob                getGameBoard()      Returns the current record's "game_board" value
 * @method integer             getGameTime()       Returns the current record's "game_time" value
 * @method timestamp           getLastActionAt()   Returns the current record's "last_action_at" value
 * @method Doctrine_Collection getHiscore()        Returns the current record's "Hiscore" collection
 * @method User                setId()             Sets the current record's "id" value
 * @method User                setEmail()          Sets the current record's "email" value
 * @method User                setFirstname()      Sets the current record's "firstname" value
 * @method User                setLastname()       Sets the current record's "lastname" value
 * @method User                setGameBoard()      Sets the current record's "game_board" value
 * @method User                setGameTime()       Sets the current record's "game_time" value
 * @method User                setLastActionAt()   Sets the current record's "last_action_at" value
 * @method User                setHiscore()        Sets the current record's "Hiscore" collection
 * 
 * @package    minesweeper
 * @subpackage model
 * @author     Laurent Raufaste
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('game_board', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('game_time', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_action_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('createdindex', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Hiscore', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
             ),
             ));
        $this->actAs($timestampable0);
    }
}