<?php

/**
 * BaseHiscore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $time
 * @property integer $boardwidth
 * @property User $User
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getUserId()     Returns the current record's "user_id" value
 * @method integer getTime()       Returns the current record's "time" value
 * @method integer getBoardwidth() Returns the current record's "boardwidth" value
 * @method User    getUser()       Returns the current record's "User" value
 * @method Hiscore setId()         Sets the current record's "id" value
 * @method Hiscore setUserId()     Sets the current record's "user_id" value
 * @method Hiscore setTime()       Sets the current record's "time" value
 * @method Hiscore setBoardwidth() Sets the current record's "boardwidth" value
 * @method Hiscore setUser()       Sets the current record's "User" value
 * 
 * @package    minesweeper
 * @subpackage model
 * @author     Laurent Raufaste
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHiscore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hiscore');
        $this->hasColumn('id', 'integer', 9, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 9,
             ));
        $this->hasColumn('user_id', 'integer', 6, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 6,
             ));
        $this->hasColumn('time', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('boardwidth', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('userindex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('boardwidthtimeindex', array(
             'fields' => 
             array(
              0 => 'boardwidth',
              1 => 'time',
             ),
             ));
        $this->index('createdindex', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade',
             'owningSide' => true));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}