<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    minesweeper
 * @subpackage model
 * @author     Laurent Raufaste
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
	public function getName()
	{
		return $this->getFirstname().' '.$this->getLastname();
	}
}
